// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Site.Data.Context;

namespace Site.Data.Migrations
{
    [DbContext(typeof(MeuDbContext))]
    [Migration("20210701225707_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Site.Business.Model.Distribuidora", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Sobre")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.HasKey("Id");

                    b.ToTable("Distribuidoras");
                });

            modelBuilder.Entity("Site.Business.Model.Filme", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<Guid>("DistribuidoraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Imagem")
                        .IsRequired()
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("varchar(2000)");

                    b.Property<decimal>("Valor")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DistribuidoraId");

                    b.ToTable("Filmes");
                });

            modelBuilder.Entity("Site.Business.Model.Filme", b =>
                {
                    b.HasOne("Site.Business.Model.Distribuidora", "Distribuidora")
                        .WithMany("Filmes")
                        .HasForeignKey("DistribuidoraId")
                        .IsRequired();

                    b.Navigation("Distribuidora");
                });

            modelBuilder.Entity("Site.Business.Model.Distribuidora", b =>
                {
                    b.Navigation("Filmes");
                });
#pragma warning restore 612, 618
        }
    }
}
